### ISSUE TITLE
random arguments error in is_writable

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/crds#303]
With version 7.1.5 and a fresh conda-dev install, I'm getting the following error. However, the error is random; sometimes all works fine.

```
$ pytest -rsx jwst/pipeline/tests/test_calwebb_spec2.py --runslow
============================================================================= test session starts ==============================================================================
platform darwin -- Python 3.5.3, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/eisenham/Documents/ssbdev/jwst, inifile: setup.cfg
collected 7 items

jwst/pipeline/tests/test_calwebb_spec2.py F......

=================================================================================== FAILURES ===================================================================================
________________________________________________________________________________ test_full_run _________________________________________________________________________________

mk_tmp_dirs = ('/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmp7v6fc68_', '/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmp2ptvz896', '/var/folders/z7/hcykr_n546s_5033t9rj5d200000zj/T/tmpvlklnq_r')

    def test_full_run(mk_tmp_dirs):
        """Make a full run with the default configuraiton"""
        tmp_current_path, tmp_data_path, tmp_config_path = mk_tmp_dirs
        exppath = path.join(DATAPATH, EXPFILE)

        args = [
            path.join(SCRIPT_DATA_PATH, 'calwebb_spec2.cfg'),
            exppath
        ]
>       Step.from_cmdline(args)

/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/tests/test_calwebb_spec2.py:52:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:143: in from_cmdline
    return cmdline.step_from_cmdline(args)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/cmdline.py:320: in step_from_cmdline
    step.run(*positional)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:361: in run
    result = self.process(*args)
/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/calwebb_spec2.py:89: in process
    asn.filename
/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/calwebb_spec2.py:148: in process_exposure_product
    input = self.assign_wcs(input)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:361: in run
    result = self.process(*args)
/Users/eisenham/Documents/ssbdev/jwst/jwst/assign_wcs/assign_wcs_step.py:58: in process
    reffile = self.get_reference_file(input_model, reftype)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py:633: in get_reference_file
    input_file, reference_file_type)
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/crds_client.py:150: in get_reference_file
    return list(get_multiple_reference_paths(input_file, [reference_file_type]).items())[0][1]
/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/crds_client.py:103: in get_multiple_reference_paths
    with crds_cache_locking.get_cache_lock():
/Users/eisenham/anaconda3/envs/spec2/lib/python3.5/site-packages/crds/core/crds_cache_locking.py:107: in get_cache_lock
    if not utils.is_writable(lockpath):
/Users/eisenham/anaconda3/envs/spec2/lib/python3.5/site-packages/crds/core/utils.py:580: in is_writable
    return no_exist and len(os.path.dirname(filepath)) and is_writable(os.path.dirname(filepath))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

filepath = '/tmp', no_exist = True

    def is_writable(filepath, no_exist=True):
        """Interpret the mode bits of `filepath` in terms of the current user and it's groups,
        returning True if any of user, group, or other have write permission on the path.

        If `filepath` doesn't exist,  return `no_exist` if the directory is writable.
        """
        if not os.path.exists(filepath):   # If file doesn't exist,  make sure directory is writable.
            return no_exist and len(os.path.dirname(filepath)) and is_writable(os.path.dirname(filepath))
        stats = os.stat(filepath)
        return bool((stats.st_mode & stat.S_IWUSR) and (stats.st_uid == os.geteuid()) or
>                   (stats.st_mode & stat.S_IWGRP) and (stats.st_gid in os.getgroups()) or
                    (stats.st_mode & stat.S_IWOTH))
E       OSError: [Errno 22] Invalid argument

/Users/eisenham/anaconda3/envs/spec2/lib/python3.5/site-packages/crds/core/utils.py:583: OSError
----------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py", line 361, in run
    result = self.process(*args)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/calwebb_spec2.py", line 89, in process
    asn.filename
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/pipeline/calwebb_spec2.py", line 148, in process_exposure_product
    input = self.assign_wcs(input)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py", line 361, in run
    result = self.process(*args)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/assign_wcs/assign_wcs_step.py", line 58, in process
    reffile = self.get_reference_file(input_model, reftype)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/step.py", line 633, in get_reference_file
    input_file, reference_file_type)
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/crds_client.py", line 150, in get_reference_file
    return list(get_multiple_reference_paths(input_file, [reference_file_type]).items())[0][1]
  File "/Users/eisenham/Documents/ssbdev/jwst/jwst/stpipe/crds_client.py", line 103, in get_multiple_reference_paths
    with crds_cache_locking.get_cache_lock():
  File "/Users/eisenham/anaconda3/envs/spec2/lib/python3.5/site-packages/crds/core/crds_cache_locking.py", line 107, in get_cache_lock
    if not utils.is_writable(lockpath):
  File "/Users/eisenham/anaconda3/envs/spec2/lib/python3.5/site-packages/crds/core/utils.py", line 580, in is_writable
    return no_exist and len(os.path.dirname(filepath)) and is_writable(os.path.dirname(filepath))
  File "/Users/eisenham/anaconda3/envs/spec2/lib/python3.5/site-packages/crds/core/utils.py", line 583, in is_writable
    (stats.st_mode & stat.S_IWGRP) and (stats.st_gid in os.getgroups()) or
OSError: [Errno 22] Invalid argument

----------------------------------------------------------------------
----------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------
2017-07-26 14:35:07,133 - stpipe.Spec2Pipeline - INFO - Spec2Pipeline instance created.
2017-07-26 14:35:07,134 - stpipe.Spec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2017-07-26 14:35:07,135 - stpipe.Spec2Pipeline.fringe - INFO - FringeStep instance created.
2017-07-26 14:35:07,136 - stpipe.Spec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2017-07-26 14:35:07,136 - stpipe.Spec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
2017-07-26 14:35:07,137 - stpipe.Spec2Pipeline.photom - INFO - PhotomStep instance created.
2017-07-26 14:35:07,139 - stpipe.Spec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2017-07-26 14:35:07,140 - stpipe.Spec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2017-07-26 14:35:07,140 - stpipe.Spec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2017-07-26 14:35:07,141 - stpipe.Spec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2017-07-26 14:35:07,142 - stpipe.Spec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2017-07-26 14:35:07,143 - stpipe.Spec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2017-07-26 14:35:07,143 - stpipe.Spec2Pipeline.pathloss - INFO - PathLossStep instance created.
2017-07-26 14:35:07,144 - stpipe.Spec2Pipeline.straylight - INFO - StraylightStep instance created.
2017-07-26 14:35:07,144 - stpipe - INFO - Hostname: inanna2.local.stsci.edu
2017-07-26 14:35:07,144 - stpipe - INFO - OS: Darwin
2017-07-26 14:35:11,011 - stpipe.Spec2Pipeline.fringe - INFO - Prefetch for FRINGE reference file is 'N/A'.
2017-07-26 14:35:12,431 - stpipe.Spec2Pipeline.extract_1d - INFO - Prefetch for EXTRACT1D reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_extract1d_0004.json'.
2017-07-26 14:35:13,247 - stpipe.Spec2Pipeline.photom - INFO - Prefetch for AREA reference file is 'N/A'.
2017-07-26 14:35:13,247 - stpipe.Spec2Pipeline.photom - INFO - Prefetch for PHOTOM reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_photom_0014.fits'.
2017-07-26 14:35:14,106 - stpipe.Spec2Pipeline.cube_build - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2017-07-26 14:35:14,106 - stpipe.Spec2Pipeline.cube_build - INFO - Prefetch for RESOL reference file is 'N/A'.
2017-07-26 14:35:15,833 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for DFLAT reference file is 'N/A'.
2017-07-26 14:35:15,833 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FFLAT reference file is 'N/A'.
2017-07-26 14:35:15,833 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for FLAT reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_flat_0244.fits'.
2017-07-26 14:35:15,833 - stpipe.Spec2Pipeline.flat_field - INFO - Prefetch for SFLAT reference file is 'N/A'.
2017-07-26 14:35:18,140 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for CAMERA reference file is 'N/A'.
2017-07-26 14:35:18,140 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for COLLIMATOR reference file is 'N/A'.
2017-07-26 14:35:18,140 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISPERSER reference file is 'N/A'.
2017-07-26 14:35:18,140 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISTORTION reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_distortion_0023.asdf'.
2017-07-26 14:35:18,140 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FILTEROFFSET reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FORE reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FPA reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUFORE reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUPOST reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUSLICER reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for MSA reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for OTE reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for REGIONS reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for SPECWCS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_specwcs_0001.fits'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for V2V3 reference file is 'N/A'.
2017-07-26 14:35:18,141 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for WAVELENGTHRANGE reference file is 'N/A'.
2017-07-26 14:35:19,396 - stpipe.Spec2Pipeline.resample_spec - INFO - Prefetch for DRIZPARS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2017-07-26 14:35:20,283 - stpipe.Spec2Pipeline.pathloss - INFO - Prefetch for PATHLOSS reference file is 'N/A'.
2017-07-26 14:35:21,167 - stpipe.Spec2Pipeline.straylight - INFO - Prefetch for STRAYMASK reference file is 'N/A'.
2017-07-26 14:35:21,234 - stpipe.Spec2Pipeline - INFO - Step Spec2Pipeline running with args ('/Users/eisenham/Documents/ssbdev/testdata/pandokia/jwcalibdev/data4/jwst_test_data/pipelines/jw00035001001_01101_00001_mirimage_rate.fits',).
2017-07-26 14:35:21,234 - stpipe.Spec2Pipeline - INFO - Starting calwebb_spec2 ...
2017-07-26 14:35:21,376 - stpipe.Spec2Pipeline - INFO - Processing product /Users/eisenham/Documents/ssbdev/testdata/pandokia/jwcalibdev/data4/jwst_test_data/pipelines/jw00035001001_01101_00001_mirimage
2017-07-26 14:35:21,377 - stpipe.Spec2Pipeline - INFO - Working on input /Users/eisenham/Documents/ssbdev/testdata/pandokia/jwcalibdev/data4/jwst_test_data/pipelines/jw00035001001_01101_00001_mirimage_rate.fits ...
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for CAMERA reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for COLLIMATOR reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISPERSER reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for DISTORTION reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_distortion_0023.asdf'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FILTEROFFSET reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FORE reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for FPA reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUFORE reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUPOST reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for IFUSLICER reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for MSA reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for OTE reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for REGIONS reference file is 'N/A'.
2017-07-26 14:35:21,891 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for SPECWCS reference file is '/Users/eisenham/Documents/ssbdev/testdata/crds-cache/references/jwst/miri/jwst_miri_specwcs_0001.fits'.
2017-07-26 14:35:21,892 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for V2V3 reference file is 'N/A'.
2017-07-26 14:35:21,892 - stpipe.Spec2Pipeline.assign_wcs - INFO - Prefetch for WAVELENGTHRANGE reference file is 'N/A'.
2017-07-26 14:35:21,926 - stpipe.Spec2Pipeline.assign_wcs - INFO - Step assign_wcs running with args (<jwst.datamodels.image.ImageModel object at 0x11aa5ae48>,).
===================================================================== 1 failed, 6 passed in 84.39 seconds ======================================================================
(spec2) [eisenham@inanna2 jwst]$
```

**Comment by stscieisenhamer** [comment]
To run this test, you will need data from `jwcalibdev:/data4/jwst_test_data/pipelines`.  A local copy will need be made:

```
cd <local_dir_to_hold_jwst_test_data>
rsyn -PLur jwcalibdev:/data4/jwst_test_data/pipelines .
export TEST_BIGDATA=<local_dir_to_hold_jwst_test_data>
```

To run the tests, you will need the [conda-dev python environment](https://confluence.stsci.edu/display/SSB/Conda-Dev+and+You#Conda-DevandYou-CheatSheet) setup, and a clone of the[ jwst repository](https://github.com/STScI-JWST/jwst).  In the conda-dev environment, from the top level of the repository clone, you can then execute the command shown in the initial report above.

Oh, and this is with a local crds cache, where `CRDS_PATH` has been set to a local directory.

**Comment by jaytmiller** [comment]
@stscieisenhamer 

Where is jwst/pipeline/tests/test_calwebb_spec2.py?

**Comment by stscieisenhamer** [comment]
That is relative to the path of wherever you [clone the repository.](https://github.com/STScI-JWST/jwst) You can find the file [here in the repository](https://github.com/STScI-JWST/jwst/blob/master/jwst/pipeline/tests/test_calwebb_spec2.py).

Note: Last week, I had been running things mostly on a linux machine, and never had the above issue. I'll run the test now on my mac, but even the few times I ran the tests on my mac, things did not fail either. I may have had a disjointed environment. I have a meeting now but will post an update before noon.

**Comment by jaytmiller** [comment]
OK,  good news,  thanks for exploring this.

**Comment by stscieisenhamer** [comment]
So, I have not been able to reproduce this issue in a while. So, I'm OK with closing this unless you think you have found something related.

**Comment by jaytmiller** [comment]
I didn't find anything,  but I did partition the expression in is_writable() into better isolated sub-expressions so we can determine which OS call failed.   Closing for now.
